### ISSUE TITLE
Datasource.c função com parâmetro errado

### ISSUE THREAD

**Issue by JokyOFC** [JokyOFC/Agenda-Eletronica#6]
Linha 14 do código da datasource.c está com os parâmetros errados deveria estar assim:

void getAllDependentsByAgeAndContactName(Contact contacts[], char dependentAge, char contactName[]) {}

porem esta desse jeito:

void getAllDependentsByAgeAndContactName(Contact contacts[], int dependentAge, char contactName[]) {}

Foi identificado observando os headers do datasource.

**Comment by EvertonMutti** [comment]
mas pq age seria um char? sendo q o age está int
